project_id = "uunaexgeunlvizbzgqrb"

[functions.create-user]
verify_jwt = true

[functions.evaluate-candidate]
verify_jwt = true

[functions.generate-job-description]
verify_jwt = true

[functions.submit-application]
verify_jwt = false
